all: test1.dat test1a.dat test2.dat test2a.dat

test1.dat: test1
	./test1

test1a.dat: test1a
	./test1a

test2.dat: test2
	./test2

test2a.dat: test2a
	./test2a

test3.dat: test3
	./test3

clean: 
	rm -f test1.dat test1a.dat test2.dat test2a.dat test3.dat

