all: test1.dat test2a.dat test2b.dat test2c.dat test3.dat

test1.dat: test1
	./test1

test2a.dat: test2a
	./test2a

test2b.dat: test2b
	./test2b

test2c.dat: test2c
	./test2c

test3.dat: test3
	./test3

clean: 
	rm -f test1.dat test2a.dat test2b.dat test2c.dat test3.dat
