#!/bin/sh
# -n 12: pink+white
# -t: fixed seed (for testing)
# -ot 99: no output
../sumi -mu 0.5 -v -n 12 -ap 0.151 -aw 0 -b 32768 -c 10000000 -t -stats -ot 99 -B 100000 -R 0.580 2>&1 | tee test3.dat
